### ISSUE TITLE
Crash on start up caused by ClassNotFoundException

### ISSUE THREAD

**Issue by mmrmartin** [veraPDF/veraPDF-apps#211]
I followed an instruction in `README.md` to install veraPDF (only exception was `verapdf-install` instead of `verapdf-install.sh`) on **Linux** leaving the default values in installation.
```Bash
wget http://downloads.verapdf.org/rel/verapdf-installer.zip
unzip verapdf-installer.zip
cd verapdf-<version>
./verapdf-install
```
I get this output during installation:
```
Jun 7, 2017 6:35:29 PM INFO: Logging initialized at level 'INFO'
Jun 7, 2017 6:35:29 PM INFO: Commandline arguments: 
Jun 7, 2017 6:35:30 PM INFO: Detected platform: suse_linux,version=4.11.3-1-default,arch=x64,symbolicName=null,javaVersion=1.8.0_121
Jun 7, 2017 6:35:30 PM WARNING: Failed to determine hostname and IP address
Jun 7, 2017 6:35:32 PM INFO: Cannot find named resource: 'packsLang.xml' AND 'packsLang.xml_eng'
Jun 7, 2017 6:36:00 PM INFO: Cleaning up the target folder ...
Jun 7, 2017 6:36:00 PM INFO: Cleaning up the target folder ...
Jun 7, 2017 6:36:00 PM INFO: Cleaning up the target folder ...
[ Writing the uninstaller data ... ]
```
When I run `verapdf` or `verapdf-gui` the app won't even start and crash. I get only this error (on both scripts is the error same).
```
martin@martin-nb ~/verapdf $ ./verapdf-gui 
Exception in thread "main" java.lang.NoClassDefFoundError: org.verapdf.gui.PDFValidationApplication
   at gnu.java.lang.MainThread.run(libgcj.so.17)
Caused by: java.lang.ClassNotFoundException: org.verapdf.gui.PDFValidationApplication not found in gnu.gcj.runtime.SystemClassLoader{urls=[], parent=gnu.gcj.runtime.ExtensionClassLoader{urls=[], parent=null}}
   at java.net.URLClassLoader.findClass(libgcj.so.17)
   at java.lang.ClassLoader.loadClass(libgcj.so.17)
   at java.lang.ClassLoader.loadClass(libgcj.so.17)
   at gnu.java.lang.MainThread.run(libgcj.so.17)
```
I use `verapdf-1.6.1` and my system info is:
```
$ uname -a
Linux martin-nb 4.11.3-1-default #1 SMP PREEMPT Thu May 25 17:55:04 UTC 2017 (7262353) x86_64 x86_64 x86_64 GNU/Linux
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by BezrukovM** [comment]
Tested on my machine and everything works fine (Debian Linux).

Could you reinstall the application and if it will still crash, then add to the first line of the launch script argument -x (after that step first line should look like "#!/bin/sh -x") and send us new output? This will print into terminal all launched commands from script.

**Comment by mmrmartin** [comment]
It was clean instalation

**Comment by mmrmartin** [comment]
I use OpenSUSE Leap ;-) It was clean installation even before, but I made a reinstall but it still crashes, so I changed the first line of `verapdf` script...
```
martin@martin-nb ~/verapdf $ head -n3 verapdf
#!/bin/sh -x
#
# This file is part of veraPDF Installer, a module of the veraPDF project.
```
```
martin@martin-nb ~/verapdf $ pwd
/home/martin/verapdf
```
```
martin@martin-nb ~/verapdf $ ./verapdf
+ PRG=./verapdf
+ '[' -h ./verapdf ']'
++ dirname ./verapdf
+ PRGDIR=.
++ cd ./
++ pwd
+ BASEDIR=/home/martin/verapdf
+ REPO=
+ cygwin=false
+ darwin=false
+ case "`uname`" in
++ uname
+ '[' -z /usr/lib64/jvm/java-1.5.0 ']'
+ false
+ '[' -z '' ']'
+ '[' -n /usr/lib64/jvm/java-1.5.0 ']'
+ '[' -x /usr/lib64/jvm/java-1.5.0/jre/sh/java ']'
+ JAVACMD=/usr/lib64/jvm/java-1.5.0/bin/java
+ '[' '!' -x /usr/lib64/jvm/java-1.5.0/bin/java ']'
+ '[' -z '' ']'
+ REPO=/home/martin/verapdf/bin
+ CLASSPATH='/home/martin/verapdf/etc:/home/martin/verapdf/bin/*'
+ ENDORSED_DIR=
+ '[' -n '' ']'
+ '[' -n '' ']'
+ false
+ exec /usr/lib64/jvm/java-1.5.0/bin/java -classpath '/home/martin/verapdf/etc:/home/martin/verapdf/bin/*' -Dfile.encoding=UTF8 '-Dapp.name=VeraPDF validation CLI' -Dapp.pid=31009 -Dapp.repo=/home/martin/verapdf/bin -Dapp.home=/home/martin/verapdf -Dbasedir=/home/martin/verapdf org.verapdf.cli.VeraPdfCli
Exception in thread "main" java.lang.NoClassDefFoundError: org.verapdf.cli.VeraPdfCli
   at gnu.java.lang.MainThread.run(libgcj.so.17)
Caused by: java.lang.ClassNotFoundException: org.verapdf.cli.VeraPdfCli not found in gnu.gcj.runtime.SystemClassLoader{urls=[], parent=gnu.gcj.runtime.ExtensionClassLoader{urls=[], parent=null}}
   at java.net.URLClassLoader.findClass(libgcj.so.17)
   at java.lang.ClassLoader.loadClass(libgcj.so.17)
   at java.lang.ClassLoader.loadClass(libgcj.so.17)
   at gnu.java.lang.MainThread.run(libgcj.so.17)
```
As I looked to the script, it uses `JAVA_HOME` but I didn't notice, that my `JAVA_HOME` points to different Java then the Oracle one.
```
$ echo $JAVA_HOME
/usr/lib64/jvm/java-1.5.0
```
```
/usr/lib64/jvm/java-1.5.0/bin/java -version
java version "1.5.0"
gij (GNU libgcj) version 6.3.1 20170331 [gcc-6-branch revision 246609]

Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
The Oracle Java is in `/usr/java/default` (I have to leave OpenJDK in my system because of dependencies). I use `update-alternatives` in my OS but sadly it doesn't affect `JAVA_HOME`. Sorry for that - I didn't noticed that - it look like a bug in my distro.

So if I use `export JAVA_HOME=/usr/java/default/;./verapdf-gui` or `export JAVA_HOME=/usr/java/default/;./verapdf` it works well. It even works well with openJDK 1.8 `export JAVA_HOME=/usr/lib64/jvm/jre-1.8.0-openjdk;./verapdf-gui`. Many thanks for help.
